# - Airflow Env variables.
substitutions:
  _COMPOSER_ENV_NAME: cicd-deploy
  _COMPOSER_REGION: asia-south1

# Access the id_github file from Secret Manager, and setup SSH
steps:
  - name: 'gcr.io/cloud-builders/git'
    secretEnv: ['SSH_KEY']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "$$SSH_KEY" >> /root/.ssh/id_rsa
        chmod 400 /root/.ssh/id_rsa
        ssh-keyscan -t rsa github.com > known_hosts.github
        cp known_hosts.github /root/.ssh/known_hosts
    volumes:
      - name: ssh
        path: /root/.ssh
        
# Clone the repository
  - name: gcr.io/cloud-builders/git
    dir: $REPO_NAME
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        git clone -b release1 https://github.com/bismay12/cicd-sonar.git
        cd cicd-sonar
        git switch -c release1
        echo 'helloworld'
        ls
    volumes:
      - name: ssh
        path: /root/.ssh
 
#Add dags to Dags folder
  - name: gcr.io/cloud-builders/gcloud
    args:
      - '-c'
      - |
        for dagfile in $(ls dags)
          do
          gcloud composer environments storage dags import \
          --environment $_COMPOSER_ENV_NAME \
          --location $_COMPOSER_REGION \
          --source dags/$$dagfile
          done
    entrypoint: bash

availableSecrets:
  secretManager:
    - versionName: projects/866354246469/secrets/SSH_KEY/versions/latest
      env: SSH_KEY
